name: Github workflow
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Nodejs
        uses: actions/setup-node@v1
      - name: Run Test
        run: npm test